# Generated by Django 4.1 on 2022-09-10 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0002_patient_is_ip_patient_is_op'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='is_ip',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_op',
        ),
    ]
