# Generated by Django 4.1 on 2022-09-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0003_remove_patient_is_ip_remove_patient_is_op'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_type',
            field=models.IntegerField(null=True),
        ),
    ]
