# Generated by Django 4.1 on 2022-09-12 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0004_patient_patient_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='path_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255)),
                ('charge', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.AddField(
            model_name='patient',
            name='admission_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='consulting_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_charge',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_type',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('medicine_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospApp.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='pathology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.IntegerField()),
                ('description', models.CharField(max_length=255, null=True)),
                ('path_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospApp.path_test')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='outpatient_bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_date', models.DateField()),
                ('total', models.IntegerField()),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospApp.doctor')),
                ('pathology', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospApp.pathology')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='inpatient_bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_date', models.DateField()),
                ('discharge_date', models.DateField()),
                ('misc', models.IntegerField()),
                ('total', models.IntegerField()),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospApp.doctor')),
                ('pathology', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospApp.pathology')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospApp.patient')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospApp.room')),
            ],
        ),
    ]
