# Generated by Django 4.1 on 2022-09-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0005_path_test_remove_patient_age_patient_admission_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=50)),
            ],
        ),
    ]
