# Generated by Django 4.1 on 2022-09-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0008_alter_patient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
