# Generated by Django 4.1 on 2022-09-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0009_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathology',
            name='test_date',
            field=models.DateField(),
        ),
    ]
