# Generated by Django 4.1 on 2022-09-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0010_alter_pathology_test_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inpatient_bill',
            name='misc',
            field=models.IntegerField(null=True),
        ),
    ]
