# Generated by Django 4.1 on 2022-09-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0011_alter_inpatient_bill_misc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inpatient_bill',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='inpatient_bill',
            name='room',
        ),
        migrations.RemoveField(
            model_name='outpatient_bill',
            name='doctor',
        ),
    ]
