# Generated by Django 4.1 on 2022-09-16 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0014_alter_outpatient_bill_pathology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outpatient_bill',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='outpatient_bill',
            name='pathology',
        ),
    ]
