# Generated by Django 4.1 on 2022-09-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0017_remove_inpatient_bill_misc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='doctor',
        ),
    ]
