# Generated by Django 4.1 on 2022-09-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0019_prescription_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
