# Generated by Django 4.1 on 2022-09-18 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0020_alter_prescription_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='inpatient_bill',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospApp.doctor'),
        ),
        migrations.AddField(
            model_name='inpatient_bill',
            name='pathology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospApp.pathology'),
        ),
        migrations.AddField(
            model_name='inpatient_bill',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospApp.room'),
        ),
        migrations.AddField(
            model_name='outpatient_bill',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospApp.doctor'),
        ),
        migrations.AddField(
            model_name='outpatient_bill',
            name='pathology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospApp.pathology'),
        ),
    ]
