# Generated by Django 4.1 on 2022-09-18 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0021_inpatient_bill_doctor_inpatient_bill_pathology_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inpatient_bill',
            name='total',
        ),
        migrations.RemoveField(
            model_name='outpatient_bill',
            name='total',
        ),
    ]
