# Generated by Django 4.1 on 2022-09-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0022_remove_inpatient_bill_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inpatient_bill',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
