# Generated by Django 4.1 on 2022-09-19 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0026_remove_inpatient_bill_doctor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
