# Generated by Django 4.1 on 2022-09-19 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0028_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
