# Generated by Django 4.1 on 2022-09-19 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0030_patient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
    ]
