# Generated by Django 4.1 on 2022-09-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0036_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='prifile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='image/patient'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='image/doctor'),
        ),
    ]
