# Generated by Django 4.1 on 2022-09-22 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0037_patient_prifile_pic_alter_doctor_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='prifile_pic',
            new_name='profile_pic',
        ),
    ]
