# Generated by Django 4.1 on 2022-12-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0038_rename_prifile_pic_patient_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='contact_num',
            field=models.IntegerField(max_length=12),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact_num',
            field=models.IntegerField(max_length=12),
        ),
    ]
